import json
import numpy as np

def fix_sonar_new(filename):
    with open(filename, 'r') as f:
        nb = json.load(f)
        
    for i, cell in enumerate(nb['cells']):
        if cell.get('cell_type') == 'code':
            source = ''.join(cell.get('source', []))
            
            if 'fs = 48000' in source and 'f0 = 20' in source and 'T = 10' in source and 'generate chirp signal' in source:
                cell['source'] = [
                    "fs = 48000\n",
                    "f0 = 20\n",
                    "f1 = 20000\n",
                    "T = 10\n",
                    "# your code here\n\n",
                    "# generate time index and phase\n",
                    "import numpy as np\n",
                    "t = np.arange(0, T, 1/fs)\n",
                    "k = (f1 - f0) / T\n",
                    "phi_of_t = 2 * np.pi * (f0 * t + 0.5 * k * t**2)\n\n",
                    "# generate chirp signal\n",
                    "s_chirp = 0.5 * np.sin(phi_of_t)\n"
                ]
            
            elif 'def genChirpPulse(' in source:
                cell['source'] = [
                    "def genChirpPulse(Npulse, f0, f1, fs):\n",
                    "    #     Function generates an analytic function of a chirp pulse\n",
                    "    #     Inputs:\n",
                    "    #             Npulse - pulse length in samples\n",
                    "    #             f0     - starting frequency of chirp\n",
                    "    #             f1     - end frequency of chirp\n",
                    "    #             fs     - sampling frequency\n",
                    "    #     Output:\n",
                    "    #              pulse - chirp pulse\n",
                    "    import numpy as np\n",
                    "    t = np.arange(Npulse) / fs\n",
                    "    k = (f1 - f0) / (Npulse / fs)\n",
                    "    phi_of_t = 2 * np.pi * (f0 * t + 0.5 * k * t**2)\n",
                    "    pulse = np.exp(1j * phi_of_t)\n",
                    "    return pulse\n"
                ]

            elif '%matplotlib inline' in source and 'pulse = genChirpPulse(' in source:
                cell['source'] = [
                    "%matplotlib inline\n",
                    "\n",
                    "pulse = genChirpPulse(200, 1000, 8000, 48000)\n",
                    "\n",
                    "# your code here:\n",
                    "import matplotlib.pyplot as plt\n",
                    "import numpy as np\n",
                    "plt.figure(figsize=(10, 4))\n",
                    "plt.plot(np.real(pulse), label='Real')\n",
                    "plt.plot(np.imag(pulse), label='Imaginary')\n",
                    "plt.legend()\n",
                    "plt.title('Chirp Pulse (Real and Imaginary)')\n",
                    "plt.xlabel('Samples')\n",
                    "plt.ylabel('Amplitude')\n",
                    "plt.show()\n"
                ]

            elif 'def genPulseTrain(' in source:
                cell['source'] = [
                    "def genPulseTrain(pulse, Nrep, Nseg):\n",
                    "    # Funtion generates a pulse train from a pulse. \n",
                    "    #Inputs:\n",
                    "    #    pulse = the pulse generated by genChirpPulse\n",
                    "    #    Nrep  =  number of pulse repetitions\n",
                    "    #    Nseg  =  Length of pulse segment >= length(pulse)\n",
                    "    import numpy as np\n",
                    "    train = np.zeros(Nrep * Nseg, dtype=complex)\n",
                    "    for i in range(Nrep):\n",
                    "        train[i*Nseg : i*Nseg + len(pulse)] = pulse\n",
                    "    return train\n"
                ]

            elif 'Npulse = 96' in source and 'f1 = 8000' in source:
                cell['source'] = [
                    "fs = 48000\n",
                    "f0 = 8000\n",
                    "f1 = 8000\n",
                    "Npulse = 96\n",
                    "\n",
                    "# your code here:\n",
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "pulse = genChirpPulse(Npulse, f0, f1, fs)\n",
                    "window = np.hanning(Npulse)\n",
                    "pulse = pulse * window\n",
                    "plt.figure(figsize=(10, 4))\n",
                    "plt.plot(np.real(pulse), label='Real')\n",
                    "plt.plot(np.imag(pulse), label='Imaginary')\n",
                    "plt.legend()\n",
                    "plt.title('Hanning Windowed Chirp Pulse')\n",
                    "plt.xlabel('Samples')\n",
                    "plt.ylabel('Amplitude')\n",
                    "plt.show()\n"
                ]

            elif i == 57 or 'your code here' in source and 'Nseg=4096' in nb['cells'][i-2].get('source', [''])[0]:
                cell['source'] = [
                    "# your code here:\n",
                    "Nrep = 15\n",
                    "Nseg = 4096\n",
                    "pulse_real = np.real(pulse)\n",
                    "ptrain = genPulseTrain(pulse_real, Nrep, Nseg)\n"
                ]

            elif '%matplotlib notebook' in source and 'your code here' in source and i == 60:
                cell['source'] = [
                    "%matplotlib notebook\n",
                    "\n",
                    "# your code here\n",
                    "rcv = xciever(ptrain * 0.5, fs)\n",
                    "import matplotlib.pyplot as plt\n",
                    "plt.figure(figsize=(10, 4))\n",
                    "plt.plot(np.real(ptrain), label='Transmitted')\n",
                    "plt.plot(np.real(rcv), label='Received')\n",
                    "plt.legend()\n",
                    "plt.title('Transmitted vs Received Pulse Train')\n",
                    "plt.xlabel('Samples')\n",
                    "plt.ylabel('Amplitude')\n",
                    "plt.show()\n"
                ]

            elif 'rcv_pulse = rcv[idx-2*Npulse:idx+Npulse*20]' in source:
                cell['source'] = [
                    "%matplotlib notebook\n",
                    "# your code here:\n",
                    "# find index of start pulse\n",
                    "idx = np.argmax(np.abs(rcv))\n",
                    "\n",
                    "rcv_pulse = rcv[max(0, idx-2*Npulse):idx+Npulse*20]\n",
                    "\n",
                    "# make plot\n",
                    "import matplotlib.pyplot as plt\n",
                    "plt.figure(figsize=(10, 4))\n",
                    "plt.plot(rcv_pulse)\n",
                    "plt.title('Received Pulse Extract')\n",
                    "plt.xlabel('Samples')\n",
                    "plt.ylabel('Amplitude')\n",
                    "plt.show()\n"
                ]

            elif 'def crossCorr(' in source:
                cell['source'] = [
                    "def crossCorr( rcv, pulse_a ):\n",
                    "    # Funtion generates cross-correlation between rcv and pulse_a\n",
                    "    # Inputs:\n",
                    "    #    rcv - received signal\n",
                    "    #    pulse_a - analytic pulse\n",
                    "    # Output:\n",
                    "    #    Xrcv - cross-correlation between rcv and pulse_a\n",
                    "    from scipy import signal\n",
                    "    import numpy as np\n",
                    "    Xrcv = signal.fftconvolve(rcv, pulse_a[::-1].conj(), mode='valid')\n",
                    "    return Xrcv\n"
                ]

            elif i == 65 and 'your code here' in source:
                cell['source'] = [
                    "%matplotlib notebook\n",
                    "\n",
                    "# your code here:\n",
                    "Xrcv = crossCorr(rcv, pulse)\n",
                    "Xrcv_a = np.abs(Xrcv)\n",
                    "import matplotlib.pyplot as plt\n",
                    "plt.figure(figsize=(10, 4))\n",
                    "plt.plot(Xrcv_a)\n",
                    "plt.title('Matched Filter Output Envelope')\n",
                    "plt.xlabel('Samples')\n",
                    "plt.ylabel('Amplitude')\n",
                    "plt.show()\n"
                ]

            elif i == 67 and 'your code here' in source:
                cell['source'] = [
                    "%matplotlib notebook\n",
                    "# your code here\n",
                    "idx_Xrcv = np.argmax(Xrcv_a)\n",
                    "rcv_pulse_mf = Xrcv_a[max(0, idx_Xrcv-2*Npulse):idx_Xrcv+Npulse*20]\n",
                    "import matplotlib.pyplot as plt\n",
                    "plt.figure(figsize=(10, 4))\n",
                    "plt.plot(rcv_pulse_mf)\n",
                    "plt.title('Received Pulse MF Extract')\n",
                    "plt.xlabel('Samples')\n",
                    "plt.ylabel('Amplitude')\n",
                    "plt.show()\n"
                ]

            elif 'def findDelay(' in source:
                cell['source'] = [
                    "def findDelay(Xrcv, Nseg):\n",
                    "    # finds the first pulse\n",
                    "    # Inputs:  \n",
                    "    #         Xrcv - the received matched filtered signal\n",
                    "    #         Nseg - length of a segment\n",
                    "    # Output:\n",
                    "    #          idx - index of the beginning of the first pulse\n",
                    "    import numpy as np\n",
                    "    idx = np.argmax(np.abs(Xrcv[:Nseg]))\n",
                    "    return idx\n"
                ]

            elif 'def dist2time(' in source:
                cell['source'] = [
                    "def dist2time( dist, temperature=21):\n",
                    "    # Converts distance in cm to time in secs\n",
                    "    # Inputs:\n",
                    "    # dist        - distance to object in cm\n",
                    "    # temperature - in celcius\n",
                    "    # Output:\n",
                    "    # t           - time in seconds between transmitted pulse and echo\n",
                    "    import numpy as np\n",
                    "    v_s = 331.3 * np.sqrt(1 + temperature / 273.15)\n",
                    "    t = 2 * (dist / 100) / v_s\n",
                    "    return t\n",
                    "\n",
                    "def  time2dist(t,temperature=21):\n",
                    "    # Converts time in seconds to distance in cm\n",
                    "    # Inputs:\n",
                    "    # t        - time of echo\n",
                    "    # temperature - in celcius\n",
                    "    # Output:\n",
                    "    # dist          - distance in cm of the target\n",
                    "    import numpy as np\n",
                    "    v_s = 331.3 * np.sqrt(1 + temperature / 273.15)\n",
                    "    dist = (t * v_s / 2) * 100\n",
                    "    return dist\n"
                ]
                
    with open(filename, 'w') as f:
        json.dump(nb, f, indent=1)
        
def fix_realtime(filename):
    with open(filename, 'r') as f:
        nb = json.load(f)
        
    for i, cell in enumerate(nb['cells']):
        if cell.get('cell_type') == 'code':
            source = ''.join(cell.get('source', []))
            if 'def genChirpPulse(' in source and 'def genPulseTrain(' in source and 'def dist2time(' in source:
                cell['source'] = [
                    "# Copy and paste your 5 functions here:\n",
                    "# genChirpPulse()\n",
                    "def genChirpPulse(Npulse, f0, f1, fs):\n",
                    "    import numpy as np\n",
                    "    t = np.arange(Npulse) / fs\n",
                    "    k = (f1 - f0) / (Npulse / fs)\n",
                    "    phi_of_t = 2 * np.pi * (f0 * t + 0.5 * k * t**2)\n",
                    "    pulse = np.exp(1j * phi_of_t)\n",
                    "    return pulse\n",
                    "\n",
                    "# genPulseTrain()\n",
                    "def genPulseTrain(pulse, Nrep, Nseg):\n",
                    "    import numpy as np\n",
                    "    train = np.zeros(Nrep * Nseg, dtype=complex)\n",
                    "    for i in range(Nrep):\n",
                    "        train[i*Nseg : i*Nseg + len(pulse)] = pulse\n",
                    "    return train\n",
                    "\n",
                    "# crossCorr()\n",
                    "def crossCorr( rcv, pulse_a ):\n",
                    "    from scipy import signal\n",
                    "    import numpy as np\n",
                    "    Xrcv = signal.fftconvolve(rcv, pulse_a[::-1].conj(), mode='valid')\n",
                    "    return Xrcv\n",
                    "\n",
                    "# findDelay()\n",
                    "def findDelay(Xrcv, Nseg):\n",
                    "    import numpy as np\n",
                    "    idx = np.argmax(np.abs(Xrcv[:Nseg]))\n",
                    "    return idx\n",
                    "\n",
                    "# dist2time()\n",
                    "def dist2time( dist, temperature=21):\n",
                    "    import numpy as np\n",
                    "    v_s = 331.3 * np.sqrt(1 + temperature / 273.15)\n",
                    "    t = 2 * (dist / 100) / v_s\n",
                    "    return t\n"
                ]

    with open(filename, 'w') as f:
        json.dump(nb, f, indent=1)

import sys
if __name__ == '__main__':
    fix_sonar_new('dsp_Sonar_project/TimeDomain-Sonar-New.ipynb')
    try:
        fix_sonar_new('dsp_Sonar_project/TimeDomain-Sonar-New (1).ipynb')
    except:
        pass
    fix_realtime('dsp_Sonar_project/TimeDomain-RealTime-Sonar.ipynb')
    print('Fixed all notebooks successfully.')
